import {
  contentTitle, contentDesc, sectionHeading, paragraph,
  codeBlock, inlineCode, note, tableWrapper
} from './Docs/docs.chain.ts';
import { docTable, docTh, docTd } from './Docs/docs.chain.ts';
import { usePrism } from '../../lib/usePrism';

export default function FrameworkCodegen() {
  usePrism([]);

  return (
    <>
      <h1 className={contentTitle}>Framework Code Generation</h1>
      <p className={contentDesc}>
        Auto-generate React, Vue, Svelte, and Solid components from your ChainCSS style
        definitions. One command creates a fully typed component with className imports,
        prop interfaces, and framework-specific patterns. Auto-detects your framework
        from package.json.
      </p>

      <h2 className={sectionHeading}>Quick Example</h2>

      <pre className={codeBlock}><code className="language-ts">{`// Input: a style definition in button.chain.ts
export const btn = chain()
  .background({ color: '#6366f1' })
  .typography({ color: '#ffffff', fontWeight: '600' })
  .box({ padding: '12px 24px', borderRadius: 8 })
  .hover().background({ color: '#4f46e5' }).end()
  .$el('btn')

// Output: auto-generated React component
// Button.tsx
import React from 'react';
import styles from './button.class.js';
import './button.css';

export interface ButtonProps {
  tag?: React.ElementType;
  className?: string;
  children?: React.ReactNode;
  [key: string]: any;
}

export const Button: React.FC<ButtonProps> = ({ 
  tag: Component = 'div', 
  className, 
  children, 
  ...props 
}) => {
  const cn = [styles['btn'], className].filter(Boolean).join(' ');
  return <Component className={cn} {...props}>{children}</Component>;
};
Button.displayName = 'ChainCSSButton';
export default Button;`}</code></pre>

      <h2 className={sectionHeading}>Framework Auto-Detection</h2>
      <p className={paragraph}>
        The code generator reads your <code className={inlineCode}>package.json</code> to detect
        which framework you're using. It checks for the framework package in this order:
      </p>

      <div className={tableWrapper}>
        <table className={docTable}>
          <thead><tr>
            <th className={docTh}>Framework</th>
            <th className={docTh}>Detection</th>
            <th className={docTh}>Generated File</th>
            <th className={docTh}>Pattern</th>
          </tr></thead>
          <tbody>{[
            ['React', 'react in dependencies', 'ComponentName.tsx', 'React.FC with displayName, prop interface'],
            ['Vue', 'vue in dependencies', 'ComponentName.vue', 'Options API with computed combinedClass'],
            ['Svelte', 'svelte in dependencies', 'ComponentName.svelte', 'Reactive $: declaration, svelte:element'],
            ['Solid', 'solid-js in dependencies', 'ComponentName.tsx', 'Dynamic component, rest props extraction'],
          ].map(([fw, detection, file, pattern], i) => (
            <tr key={i}>
              <td className={docTd}><strong>{fw}</strong></td>
              <td className={docTd} style={{ fontSize: 13, fontFamily: 'monospace' }}>{detection}</td>
              <td className={docTd} style={{ fontSize: 13, fontFamily: 'monospace' }}>{file}</td>
              <td className={docTd} style={{ fontSize: 13 }}>{pattern}</td>
            </tr>
          ))}</tbody>
        </table>
      </div>

      <h2 className={sectionHeading}>Generated Component: Vue</h2>

      <pre className={codeBlock}><code className="language-html">{`<!-- Auto-generated by ChainCSS -->
<template>
  <component :is="tag" :class="combinedClass" v-bind="$attrs">
    <slot />
  </component>
</template>

<script>
import styles from './button.class.js';
import './button.css';

export default {
  name: 'ChainCSSButton',
  props: {
    tag: { type: String, default: 'div' },
    className: { type: String, default: '' }
  },
  computed: {
    combinedClass() {
      return [styles['btn'], this.className].filter(Boolean).join(' ');
    }
  }
};
</script>`}</code></pre>

      <h2 className={sectionHeading}>Generated Component: Svelte</h2>

      <pre className={codeBlock}><code className="language-html">{`<!-- Auto-generated by ChainCSS -->
<script>
  import styles from './button.class.js';
  import './button.css';
  
  export let className = '';
  export let tag = 'div';
  
  $: combinedClass = [styles['btn'], className].filter(Boolean).join(' ');
</script>

<svelte:element this={tag} class={combinedClass}>
  <slot />
</svelte:element>`}</code></pre>

      <h2 className={sectionHeading}>Generated Component: Solid</h2>

      <pre className={codeBlock}><code className="language-tsx">{`// Auto-generated by ChainCSS
import { Dynamic } from 'solid-js/web';
import styles from './button.class.js';
import './button.css';

export function Button(props: any) {
  const tag = () => props.tag || 'div';
  const cn = () => [styles['btn'], props.class].filter(Boolean).join(' ');
  
  const restProps = () => {
    const { tag, class: _, children, ...rest } = props;
    return rest;
  };

  return (
    <Dynamic component={tag()} class={cn()} {...restProps()}>
      {props.children}
    </Dynamic>
  );
}`}</code></pre>

      <h2 className={sectionHeading}>Component Name Generation</h2>
      <p className={paragraph}>
        Component names are derived from the style definition's selector using PascalCase
        conversion. Reserved words get a <code className={inlineCode}>Component</code> suffix:
      </p>

      <div className={tableWrapper}>
        <table className={docTable}>
          <thead><tr>
            <th className={docTh}>Style Name / Selector</th>
            <th className={docTh}>Generated Component Name</th>
          </tr></thead>
          <tbody>{[
            ['my-button', 'MyButton'],
            ['card_section', 'CardSection'],
            ['btn', 'Btn'],
            ['class', 'ClassComponent (reserved word)'],
            ['default', 'DefaultComponent (reserved word)'],
            ['export', 'ExportComponent (reserved word)'],
          ].map(([style, component], i) => (
            <tr key={i}>
              <td className={docTd} style={{ fontFamily: 'monospace', fontSize: 13 }}>{style}</td>
              <td className={docTd} style={{ fontFamily: 'monospace', fontSize: 13, color: '#4ade80' }}>{component}</td>
            </tr>
          ))}</tbody>
        </table>
      </div>

      <h2 className={sectionHeading}>Prop Type Generation (React)</h2>
      <p className={paragraph}>
        If you provide a props definition, the generator creates a typed interface:
      </p>

      <pre className={codeBlock}><code className="language-ts">{`// Input props definition
const propsDefinition = {
  variant: 'string',
  size: 'number',
  disabled: 'boolean',
  onClick: 'any'
}

// Generated interface
export interface ButtonProps {
  tag?: React.ElementType;
  className?: string;
  children?: React.ReactNode;
  variant?: string;
  size?: number;
  disabled?: boolean;
  onClick?: any;
}`}</code></pre>

      <h2 className={sectionHeading}>Using the Code Generator</h2>

      <pre className={codeBlock}><code className="language-ts">{`import { generateComponentCode } from 'chaincss'

const componentCode = generateComponentCode({
  name: 'button',                    // Style definition name
  selector: '.chain-btn',            // The generated CSS selector
  styles: { /* your style object */ },
  framework: 'auto',                 // 'react' | 'vue' | 'svelte' | 'solid' | 'auto'
  propsDefinition: {                 // Optional typed props
    variant: 'string',
    disabled: 'boolean'
  }
})

// componentCode contains the full component source
// Write it to a file or use it in your build pipeline`}</code></pre>

      <div className={note}>
        <strong>💡 Build-time generation:</strong> The code generator is designed to run at
        build time. Use it in your build pipeline to auto-generate wrapper components for
        every <code className={inlineCode}>.chain.ts</code> file. Each generated component imports
        its <code className={inlineCode}>.class.js</code> and <code className={inlineCode}>.css</code> files
        automatically. See <a href="/docs/frameworks" style={{ color: '#818cf8' }}>Framework Integration</a> for
        runtime usage with <code className={inlineCode}>useChainStyles()</code>.
      </div>
    </>
  );
}