// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const intentCard = 'chain-intent-card';
export const intentContainer = 'chain-intent-container';
export const intentPreviewBox = 'chain-intent-preview';
export const intentSubtitle = 'chain-intent-subtitle';
export const intentTitle = 'chain-intent-title';