/** ChainCSS Generated — DO NOT EDIT */

export const container = 'playground-container'
export const header = 'playground-header'
export const title = 'playground-title'
export const description = 'playground-description'
export const templateButtons = 'template-buttons'
export const templateBtn = 'template-btn'
export const activeTemplateBtn = 'template-btn-active'
export const playgroundGrid = 'playground-grid'
export const editorSection = 'editor-section'
export const previewSection = 'preview-section'
export const sectionHeader = 'section-header'
export const codeInputDark = 'code-input-dark'
export const previewArea = 'preview-area'
export const cssOutputSection = 'css-output'
export const chaincssButton = 'chaincss-button'
export const chaincssCard = 'chaincss-card'
export const chaincssGradient = 'chaincss-gradient'
export const copyBtn = 'copy-btn'