import { $ } from 'chaincss';

export const primaryButton = $()
  .backgroundColor('white')
  .color('#667eea')
  .padding('0.875rem 2rem')
  .fontWeight('700')
  .borderRadius('9999px')
  .border('none')
  .boxShadow('0 10px 15px -3px rgba(0,0,0,0.1)')
  .hover()
    .backgroundColor('#f1f5f9')
    .scale(1.05)
    .translateY('-2px')
    .end()
  .transition('all 0.2s ease')
  .cursor('pointer')
  .block();

export const secondaryButton = $()
  .backgroundColor('transparent')
  .textDecoration('none')
  .color('white')
  .border('2px solid white')
  .padding('0.875rem 2rem')
  .fontWeight('600')
  .borderRadius('9999px')
  .hover()
    .backgroundColor('rgba(255,255,255,0.1)')
    .scale(1.05)
    .end()
  .transition('all 0.2s ease')
  .cursor('pointer')
  .block();