// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const card = 'chain-feature-card'
export const cardCode = 'chain-feature-card-code'
export const cardIcon = 'chain-feature-card-icon'
export const cardText = 'chain-feature-card-text'
export const cardTitle = 'chain-feature-card-title'
export const grid = 'chain-feature-grid'
export const section = 'chain-features-section'
export const sectionLabel = 'chain-section-label'
export const sectionSubtitle = 'chain-section-subtitle'
export const sectionTitle = 'chain-section-title'