// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const heroSection = 'chain-hero'
export const heroBadge = 'chain-hero-badge'
export const heroTitle = 'chain-hero-title'
export const heroGradient = 'chain-hero-gradient'
export const heroSubtitle = 'chain-hero-subtitle'
export const heroCtaGroup = 'chain-hero-cta-group'
export const heroPrimaryBtn = 'chain-hero-primary-btn'
export const heroSecondaryBtn = 'chain-hero-secondary-btn'