// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const logo = 'chain-nav-logo'
export const logoAccent = 'chain-nav-logo-accent'
export const nav = 'chain-nav'
export const navCta = 'chain-nav-cta'
export const navInner = 'chain-nav-inner'
export const navLink = 'chain-nav-link'
export const navLinks = 'chain-nav-links'