// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const pgContainer = 'chain-pg-container'
export const pgCopyBtn = 'chain-pg-copy-btn'
export const pgDesc = 'chain-pg-desc'
export const pgEditor = 'chain-pg-editor'
export const pgGrid = 'chain-pg-grid'
export const pgHeader = 'chain-pg-header'
export const pgOutput = 'chain-pg-output'
export const pgPanel = 'chain-pg-panel'
export const pgPanelHeader = 'chain-pg-panel-header'
export const pgPanelTitle = 'chain-pg-panel-title'
export const pgPreview = 'chain-pg-preview'
export const pgRunBtn = 'chain-pg-run-btn'
export const pgTitle = 'chain-pg-title'