import { chain } from 'chaincss'

// ============================================================
// STATIC STYLES
// ============================================================

export const playgroundSection = chain()
  .paddingTop(100)
  .paddingLeft(24)
  .paddingRight(24)
  .paddingBottom(60)
  .maxWidth(1400)
  .margin('0 auto')
  .media('(max-width: 640px)', (c) => c
    .paddingTop(80)
    .paddingLeft(16)
    .paddingRight(16)
    .paddingBottom(40)
  )
  .$el('playground-section')

export const wrapper = chain()
  .display('grid')
  .gridTemplateColumns('repeat(auto-fit, minmax(340px, 1fr))')
  .gap(24)
  .marginTop(24)
  .media('(max-width: 640px)', (c) => c
    .gridTemplateColumns('1fr')
    .gap(16)
  )
  .$el('playground-wrapper')

export const panel = chain()
  .background('rgba(15, 23, 42, 0.8)')
  .border('1px solid rgba(99, 102, 241, 0.2)')
  .borderRadius(12)
  .padding(24)
  .media('(max-width: 640px)', (c) => c
    .padding(16)
  )
  .$el('playground-panel')

export const panelTitle = chain()
  .textAlign('center')
  .fontSize(15)
  .fontWeight(600)
  .color('#e2e8f0')
  .marginBottom(16)
  .$el('playground-panel-title')

export const runButton = chain()
  .display('flex')
  .alignItems('center')
  .justifyContent('center')
  .background('#6366f1')
  .color('#ffffff')
  .border('none')
  .borderRadius(8)
  .padding('10px 20px')
  .fontSize(14)
  .fontWeight(600)
  .cursor('pointer')
  .transition('all 0.2s ease')
  .margin('12px auto 0px')
  .width('fit-content')
  .hover()
    .background('#4f46e5')
    .transform('scale(1.02)')
  .end()
  .$el('playground-run')

export const tabs = chain()
  .display('flex')
  .gap(0)
  .margin('0 auto 24px') 
  .background('rgba(15, 23, 42, 0.5)')
  .borderRadius(10)
  .padding(4)
  .width('fit-content')
  .$el('playground-tabs')

export const codeDisplay = chain()
  .background('#0f172a')
  .borderRadius(8)
  .padding(16)
  .fontSize(13)
  .color('#e2e8f0')
  .overflow('auto')
  .maxHeight(240)
  .border('1px solid rgba(99, 102, 241, 0.3)')
  .media('(max-width: 640px)', (c) => c
    .fontSize(11)
    .maxHeight(180)
  )
  .$el('playground-code')

export const outputDisplay = chain()
  .background('#0f172a')
  .borderRadius(8)
  .padding(16)
  .fontSize(13)
  .color('#4ade80')
  .overflow('auto')
  .maxHeight(240)
  .border('1px solid rgba(16, 185, 129, 0.3)')
  .minHeight(200)
  .media('(max-width: 640px)', (c) => c
    .fontSize(11)
    .maxHeight(180)
    .minHeight(120)
  )
  .$el('playground-output-display')

export const demoSection = chain()
  .marginTop(48)
  .$el('demo-section')

export const demoDescription = chain()
  .textAlign('center')
  .color('#94a3b8')
  .fontSize(14)
  .marginBottom(24)
  .lineHeight(1.7)
  .$el('demo-description')

export const controlBar = chain()
  .display('flex')
  .gap(16)
  .margin('0 auto 24px')
  .alignItems('center')
  .justifyContent('center')
  .flexWrap('wrap')
  .width('fit-content')
  .media('(max-width: 640px)', (c) => c
    .flexDirection('column')
    .width('100%')
  )
  .$el('control-bar')

export const infoBox = chain()
  .marginTop(48)
  .textAlign('center')
  .padding(24)
  .background('rgba(99, 102, 241, 0.08)')
  .borderRadius(12)
  .border('1px solid rgba(99, 102, 241, 0.15)')
  .$el('info-box')

export const infoTitle = chain()
  .color('#e2e8f0')
  .fontSize(16)
  .fontWeight(600)
  .marginBottom(12)
  .$el('info-title')

export const infoList = chain()
  .color('#94a3b8')
  .fontSize(14)
  .lineHeight(2.2)
  .textAlign('center')
  .listStyleType('none')
  .margin(0)
  .padding(0)
  .$el('info-list')

export const previewTitle = chain()
  .fontSize(24)
  .fontWeight(700)
  .marginBottom(12)
  .$el('preview-title')

export const previewText = chain()
  .fontSize(14)
  .opacity(0.7)
  .lineHeight(1.7)
  .$el('preview-text')

// ============================================================
// DYNAMIC STYLES (Mixed Mode)
// ============================================================

export const themeToggle = chain.dynamic()
  .display('inline-flex')
  .alignItems('center')
  .gap(8)
  .padding('12px 24px')
  .borderRadius(8)
  .fontSize(14)
  .fontWeight(600)
  .cursor('pointer')
  .border('1px solid rgba(99, 102, 241, 0.3)')
  .transition('all 0.2s ease')
  .background(() => (window as any).__css_isDark ? '#1e293b' : '#f1f5f9')
  .color(() => (window as any).__css_isDark ? '#e2e8f0' : '#0f172a')
  .$el('theme-toggle')

export const counterBadge = chain.dynamic()
  .display('inline-flex')
  .alignItems('center')
  .justifyContent('center')
  .minWidth(44)
  .height(44)
  .borderRadius(9999)
  .fontSize(14)
  .fontWeight(700)
  .color('#ffffff')
  .cursor('pointer')
  .border('none')
  .transition('all 0.2s ease')
  .padding('0 16px')
  .background(() => (window as any).__css_count > 10 ? '#ef4444' : '#6366f1')
  .transform(() => (window as any).__css_count > 10 ? 'scale(1.1)' : 'scale(1)')
  .$el('counter-badge')

export const previewCard = chain.dynamic()
  .width('100%')
  .padding(40)
  .borderRadius(16)
  .textAlign('center')
  .media('(max-width: 640px)', (c) => c
    .padding(24)
  )
  .transition('all 0.3s ease')
  .border('1px solid rgba(99, 102, 241, 0.15)')
  .background(() => (window as any).__css_isDark
    ? 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)'
    : 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)'
  )
  .color(() => (window as any).__css_isDark ? '#f1f5f9' : '#0f172a')
  .shadow(() => (window as any).__css_isDark
    ? '0 20px 60px rgba(0,0,0,0.5)'
    : '0 4px 12px rgba(0,0,0,0.1)'
  )
  .$el('preview-card')
