// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const codeDisplay = 'chain-playground-code';
export const controlBar = 'chain-control-bar';
export const counterBadge = {
  className: 'chain-counter-badge',
  selectors: ['.chain-counter-badge'],
  dynamic: {
    "backgroundColor": (ctx) => ctx.count > 10 ? '#ef4444' : '#6366f1',
  }
};
export const demoDescription = 'chain-demo-description';
export const demoSection = 'chain-demo-section';
export const infoBox = 'chain-info-box';
export const infoList = 'chain-info-list';
export const infoTitle = 'chain-info-title';
export const outputDisplay = 'chain-playground-output-display';
export const panel = 'chain-playground-panel';
export const panelTitle = 'chain-playground-panel-title';
export const playgroundSection = 'chain-playground-section';
export const previewCard = {
  className: 'chain-preview-card',
  selectors: ['.chain-preview-card'],
  dynamic: {
    "background": (ctx) => ctx.isDark ?
  'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)' :
  'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
    "boxShadow": (ctx) => ctx.isDark ?
  '0 20px 60px rgba(0,0,0,0.5)' :
  '0 4px 12px rgba(0,0,0,0.1)',
    "color": (ctx) => ctx.isDark ? '#f1f5f9' : '#0f172a',
  }
};
export const previewText = 'chain-preview-text';
export const previewTitle = 'chain-preview-title';
export const runButton = 'chain-playground-run';
export const tabs = 'chain-playground-tabs';
export const themeToggle = {
  className: 'chain-theme-toggle',
  selectors: ['.chain-theme-toggle'],
  dynamic: {
    "backgroundColor": (ctx) => ctx.isDark ? '#1e293b' : '#f1f5f9',
    "color": (ctx) => ctx.isDark ? '#e2e8f0' : '#0f172a',
  }
};
export const wrapper = 'chain-playground-wrapper';