// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const actionButton = 'chain-tokens-action-btn';
export const derivedCard = 'chain-tokens-derived-card';
export const sandboxCard = 'chain-tokens-sandbox';
export const tokensContainer = 'chain-tokens-container';
export const tokensSubtitle = 'chain-tokens-subtitle';
export const tokensTitle = 'chain-tokens-title';