// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const check = 'chain-comparison-check';
export const cross = 'chain-comparison-cross';
export const partial = 'chain-comparison-partial';
export const table = 'chain-comparison-table';
export const td = 'chain-comparison-td';
export const th = 'chain-comparison-th';
export const wrapper = 'chain-comparison-wrapper';