// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const colorInput = 'chain-theme-graph-color-input';
export const colorPicker = 'chain-theme-graph-color-picker';
export const controlGroup = 'chain-theme-graph-control-group';
export const controlLabel = 'chain-theme-graph-control-label';
export const controls = 'chain-theme-graph-controls';
export const exportBtn = 'chain-theme-graph-export-btn';
export const exportHint = 'chain-theme-graph-export-hint';
export const exportSection = 'chain-theme-graph-export';
export const fileInput = 'chain-theme-graph-file-input';
export const header = 'chain-theme-graph-header';
export const modeBtn = 'chain-theme-graph-mode-btn';
export const page = 'chain-theme-graph-page';
export const paletteGrid = 'chain-theme-graph-palette-grid';
export const paletteSection = 'chain-theme-graph-palette-section';
export const previewGrid = 'chain-theme-graph-preview-grid';
export const quickPickBtn = 'chain-theme-graph-quick-pick';
export const sectionTitle = 'chain-theme-graph-section-title';
export const semanticTokens = 'chain-theme-graph-semantic-tokens';
export const subtitle = 'chain-theme-graph-subtitle';
export const title = 'chain-theme-graph-title';