// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const figmaButton = 'chain-figma-btn';
export const figmaCard = 'chain-figma-card';
export const figmaContainer = 'chain-figma-container';
export const figmaSubtitle = 'chain-figma-subtitle';
export const figmaTitle = 'chain-figma-title';