import { chain } from 'chaincss'

export const buttonPrimary = chain()
  .background({ color: '#6366f1' })
  .typography({ fontSize: 14, fontWeight: '600', color: '#ffffff' })
  .box({ padding: '10px 24px', borderRadius: 8, border: 'none' })
  .raw('cursor', 'pointer')
  .transition({ tr: 'all 0.15s ease' })
  .hover()
    .background({ color: '#4f46e5' })
  .end()
  .$el('btn-primary')

export const buttonSecondary = chain()
  .background({ color: 'transparent' })
  .typography({ fontSize: 14, fontWeight: '500' })
  .box({ padding: '10px 24px', borderRadius: 8, border: '1px solid rgba(255, 255, 255, 0.1)' })
  .raw('cursor', 'pointer')
  .transition({ tr: 'all 0.15s ease' })
  .hover()
    .background({ color: 'rgba(255, 255, 255, 0.08)' })
  .end()
  .$el('btn-secondary')

export const card = chain()
  .background({ color: 'rgba(0, 0, 0, 0.3)' })
  .box({ padding: 24, borderRadius: 12, border: '1px solid rgba(255, 255, 255, 0.06)' })
  .$el('card')

export const themeCodeBlock = chain()
  .background({ color: '#0f172a' })
  .box({ padding: '16px 20px', borderRadius: 8, overflow: 'auto', border: '1px solid rgba(99, 102, 241, 0.3)' })
  .typography({ fontFamily: "'JetBrains Mono', 'Fira Code', monospace", fontSize: 13, lineHeight: '1.7'})
  .$el('codeBlock')

export const input = chain()
  .background({ color: 'rgba(0, 0, 0, 0.4)' })
  .box({ padding: '10px 14px', borderRadius: 8, border: '1px solid rgba(255, 255, 255, 0.1)', width: '100%' })
  .typography({ fontSize: 14, color: '#e4e4e7' })
  .raw('outline', 'none')
  .focus()
    .raw('border-color', '#6366f1')
  .end()
  .$el('input')

export const badge = chain()
  .flex({ align: 'center', gap: 8 })
  .raw('display', 'inline-flex')
  .background({ color: 'rgba(99, 102, 241, 0.1)' })
  .typography({ fontSize: 13, fontWeight: '500', color: '#a5b4fc' })
  .box({ padding: '4px 12px', borderRadius: 9999 })
  .$el('badge')

export const link = chain()
  .typography({ fontSize: 14, color: '#a1a1aa', textDecoration: 'none' })
  .raw('cursor', 'pointer')
  .transition({ tr: 'color 0.15s ease' })
  .hover()
    .typography({ color: '#ffffff' })
  .end()
  .$el('link')

export const table = chain()
  .box({ width: '100%' })
  .typography({ fontSize: 14 })
  .raw('borderCollapse', 'collapse')
  .$el('table')

export const tableHeader = chain()
  .box({ padding: '12px 16px', borderBottom: '1px solid rgba(255, 255, 255, 0.08)' })
  .typography({ fontSize: 13, fontWeight: '600', letterSpacing: '0.5px', textTransform: 'uppercase', textAlign: 'left' })
  .$el('table-th')

export const tableCell = chain()
  .box({ padding: '10px 16px', borderBottom: '1px solid rgba(255, 255, 255, 0.04)' })
  .$el('table-td')
