// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const badge = 'chain-badge';
export const buttonPrimary = 'chain-btn-primary';
export const buttonSecondary = 'chain-btn-secondary';
export const card = 'chain-card';
export const input = 'chain-input';
export const link = 'chain-link';
export const table = 'chain-table';
export const tableCell = 'chain-table-td';
export const tableHeader = 'chain-table-th';
export const themeCodeBlock = 'chain-codeBlock';