// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const body = 'chain-body';
export const bodyLarge = 'chain-body-lg';
export const bodySmall = 'chain-body-sm';
export const caption = 'chain-caption';
export const heading1 = 'chain-h1';
export const heading2 = 'chain-h2';
export const heading3 = 'chain-h3';
export const heading4 = 'chain-h4';
export const mono = 'chain-mono';
export const monoSmall = 'chain-mono-sm';
export const container = 'chain-container';
export const flexBetween = 'chain-flex-between';
export const flexCenter = 'chain-flex-center';
export const flexCol = 'chain-flex-col';
export const grid = 'chain-grid';
export const section = 'chain-section';
export const badge = 'chain-badge';
export const buttonPrimary = 'chain-btn-primary';
export const buttonSecondary = 'chain-btn-secondary';
export const card = 'chain-card';
export const input = 'chain-input';
export const link = 'chain-link';
export const table = 'chain-table';
export const tableCell = 'chain-table-td';
export const tableHeader = 'chain-table-th';
export const themeCodeBlock = 'chain-codeBlock';