// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const container = 'chain-container';
export const flexBetween = 'chain-flex-between';
export const flexCenter = 'chain-flex-center';
export const flexCol = 'chain-flex-col';
export const grid = 'chain-grid';
export const section = 'chain-section';