// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const body = 'chain-body';
export const bodyLarge = 'chain-body-lg';
export const bodySmall = 'chain-body-sm';
export const caption = 'chain-caption';
export const heading1 = 'chain-h1';
export const heading2 = 'chain-h2';
export const heading3 = 'chain-h3';
export const heading4 = 'chain-h4';
export const mono = 'chain-mono';
export const monoSmall = 'chain-mono-sm';